name: Testypants
favicon: null
layout_spectrum: 0.04320719884708524
typography_spectrum: 0.9126792957540601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5232021403498948
  lightness: 0.4273643030319363
  saturation: 0.3168307233136147
  rhythmicContrast: 0.3503956387285143
purpose: []
